import type { UniversityPreset } from '../types';

export const UNIVERSITY_PRESETS: UniversityPreset[] = [
    // --- UNITED KINGDOM ---
    { name: 'University of Edinburgh', country: 'UK', locations: [{ name: "Main Library (George Sq)", lat: 55.9427, lng: -3.1890 }, { name: "Appleton Tower", lat: 55.9400, lng: -3.1857 }, { name: "King's Buildings", lat: 55.9203, lng: -3.1717 }] },
    { name: 'Heriot-Watt University', country: 'UK', locations: [{ name: "Riccarton Campus Library", lat: 55.9080, lng: -3.3210 }, { name: "Student Union", lat: 55.9100, lng: -3.3230 }] },
    { name: 'Edinburgh Napier University', country: 'UK', locations: [{ name: "Merchiston Campus", lat: 55.9324, lng: -3.2120 }, { name: "Sighthill Campus", lat: 55.9240, lng: -3.2880 }] },
    { name: 'Imperial College London', country: 'UK', locations: [{ name: "South Kensington Campus", lat: 51.4988, lng: -0.1749 }] },
    { name: 'University of Manchester', country: 'UK', locations: [{ name: "Main Library", lat: 53.4675, lng: -2.2330 }] },
    { name: 'University of Oxford', country: 'UK', locations: [{ name: "Radcliffe Camera", lat: 51.7534, lng: -1.2540 }] },
    { name: 'University of Cambridge', country: 'UK', locations: [{ name: "University Library", lat: 52.2025, lng: 0.1085 }] },
    { name: 'University of Glasgow', country: 'UK', locations: [{ name: "Main Building", lat: 55.8720, lng: -4.2882 }] },
    { name: 'University of Strathclyde', country: 'UK', locations: [{ name: "John Anderson Campus", lat: 55.8624, lng: -4.2464 }] },
    { name: 'University of Bristol', country: 'UK', locations: [{ name: "Wills Memorial Library", lat: 51.4582, lng: -2.6015 }] },
    { name: 'University of Leeds', country: 'UK', locations: [{ name: "Brotherton Library", lat: 53.8077, lng: -1.5540 }] },
    { name: 'University of Sheffield', country: 'UK', locations: [{ name: "The Diamond", lat: 53.3814, lng: -1.4884 }] },
    { name: 'University of Nottingham', country: 'UK', locations: [{ name: "University Park", lat: 52.9366, lng: -1.1920 }] },
    { name: 'University of Birmingham', country: 'UK', locations: [{ name: "Old Joe Clock Tower", lat: 52.4508, lng: -1.9305 }] },
    { name: 'University of Warwick', country: 'UK', locations: [{ name: "Library", lat: 52.3797, lng: -1.5615 }] },
    { name: 'University of Southampton', country: 'UK', locations: [{ name: "Highfield Campus", lat: 50.9348, lng: -1.3962 }] },
    { name: 'University of Aberdeen', country: 'UK', locations: [{ name: "Sir Duncan Rice Library", lat: 57.1645, lng: -2.1020 }] },
    { name: 'University of St Andrews', country: 'UK', locations: [{ name: "St Salvator's Quad", lat: 56.3417, lng: -2.7944 }] },
    { name: 'Loughborough University', country: 'UK', locations: [{ name: "Pilkington Library", lat: 52.7667, lng: -1.2333 }] },
    { name: 'Lancaster University', country: 'UK', locations: [{ name: "The Spine", lat: 54.0104, lng: -2.7847 }] },
    { name: 'University of Bath', country: 'UK', locations: [{ name: "The Lake", lat: 51.3810, lng: -2.3275 }] },
    { name: 'University of Exeter', country: 'UK', locations: [{ name: "Forum", lat: 50.7350, lng: -3.5350 }] },
    { name: 'University of York', country: 'UK', locations: [{ name: "Central Hall", lat: 53.9450, lng: -1.0500 }] },
    { name: 'University of Liverpool', country: 'UK', locations: [{ name: "Victoria Building", lat: 53.4060, lng: -2.9660 }] },
    { name: 'Newcastle University', country: 'UK', locations: [{ name: "Armstrong Building", lat: 54.9790, lng: -1.6160 }] },
    { name: 'Durham University', country: 'UK', locations: [{ name: "Palace Green", lat: 54.7750, lng: -1.5760 }] },
    { name: 'University of Dundee', country: 'UK', locations: [{ name: "Main Campus", lat: 56.4580, lng: -2.9830 }] },
    { name: 'University of Stirling', country: 'UK', locations: [{ name: "Airthrey Loch", lat: 56.1495, lng: -3.9220 }] },
    { name: 'Robert Gordon University', country: 'UK', locations: [{ name: "Garthdee", lat: 57.1180, lng: -2.1380 }] },
    { name: 'Queen\'s University Belfast', country: 'UK', locations: [{ name: "Lanyon Building", lat: 54.5847, lng: -5.9348 }] },
    { name: 'King\'s College London', country: 'UK', locations: [{ name: "Bush House", lat: 51.5135, lng: -0.1170 }] },
    { name: 'University College London (UCL)', country: 'UK', locations: [{ name: "The Portico", lat: 51.5246, lng: -0.1340 }] },
    { name: 'London School of Economics (LSE)', country: 'UK', locations: [{ name: "Saw Swee Hock", lat: 51.5140, lng: -0.1160 }] },
    { name: 'Cardiff University', country: 'UK', locations: [{ name: "Main Building", lat: 51.4880, lng: -3.1790 }] },
    { name: 'Swansea University', country: 'UK', locations: [{ name: "Singleton Park", lat: 51.6090, lng: -3.9800 }] },
    { name: 'University of Reading', country: 'UK', locations: [{ name: "Whiteknights", lat: 51.4410, lng: -0.9420 }] },
    { name: 'University of Sussex', country: 'UK', locations: [{ name: "Falmer", lat: 50.8670, lng: -0.0880 }] },
    { name: 'University of Surrey', country: 'UK', locations: [{ name: "Stag Hill", lat: 51.2430, lng: -0.5890 }] },
    { name: 'University of Kent', country: 'UK', locations: [{ name: "Canterbury Campus", lat: 51.2970, lng: 1.0690 }] },
    { name: 'University of East Anglia', country: 'UK', locations: [{ name: "The Ziggurats", lat: 52.6210, lng: 1.2390 }] },
    { name: 'University of Essex', country: 'UK', locations: [{ name: "Colchester Campus", lat: 51.8770, lng: 0.9450 }] },
    { name: 'University of Leicester', country: 'UK', locations: [{ name: "Victoria Park", lat: 52.6210, lng: -1.1240 }] },
    { name: 'Aston University', country: 'UK', locations: [{ name: "Main Building", lat: 52.4860, lng: -1.8890 }] },
    { name: 'Coventry University', country: 'UK', locations: [{ name: "The Hub", lat: 52.4080, lng: -1.5030 }] },
    { name: 'Brighton University', country: 'UK', locations: [{ name: "Moulsecoomb", lat: 50.8420, lng: -0.1180 }] },
    { name: 'Aberystwyth University', country: 'UK', locations: [{ name: "Penglais Campus", lat: 52.4160, lng: -4.0660 }] },
    { name: 'Bangor University', country: 'UK', locations: [{ name: "Main Arts Building", lat: 53.2280, lng: -4.1300 }] },
    { name: 'City University London', country: 'UK', locations: [{ name: "Northampton Square", lat: 51.5280, lng: -0.1020 }] },
    { name: 'Brunel University London', country: 'UK', locations: [{ name: "Uxbridge Campus", lat: 51.5330, lng: -0.4730 }] },
    { name: 'Royal Holloway University', country: 'UK', locations: [{ name: "Founder's Building", lat: 51.4250, lng: -0.5630 }] },
    { name: 'Oxford Brookes University', country: 'UK', locations: [{ name: "Gipsy Lane", lat: 51.7540, lng: -1.2220 }] },
    { name: 'Bournemouth University', country: 'UK', locations: [{ name: "Talbot Campus", lat: 50.7430, lng: -1.8970 }] },
    { name: 'Huddersfield University', country: 'UK', locations: [{ name: "Queensgate", lat: 53.6430, lng: -1.7770 }] },
    { name: 'University of Portsmouth', country: 'UK', locations: [{ name: "Guildhall", lat: 50.7980, lng: -1.0910 }] },
    { name: 'Plymouth University', country: 'UK', locations: [{ name: "City Centre", lat: 50.3750, lng: -4.1390 }] },
    { name: 'Hertfordshire University', country: 'UK', locations: [{ name: "College Lane", lat: 51.7520, lng: -0.2430 }] },
    { name: 'Salford University', country: 'UK', locations: [{ name: "Peel Park", lat: 53.4850, lng: -2.2700 }] },
    { name: 'Teesside University', country: 'UK', locations: [{ name: "Middlesbrough", lat: 54.5720, lng: -1.2340 }] },
    { name: 'Ulster University', country: 'UK', locations: [{ name: "Belfast Campus", lat: 54.6030, lng: -5.9290 }] },

    // --- MALAYSIA ---
    { name: 'University of Malaya (UM)', country: 'Malaysia', locations: [{ name: "DTC", lat: 3.1205, lng: 101.6535 }, { name: "Main Library", lat: 3.1215, lng: 101.6540 }] },
    { name: 'Universiti Teknologi Malaysia (UTM)', country: 'Malaysia', locations: [{ name: "Skudai Campus Library", lat: 1.5585, lng: 103.6385 }, { name: "KL Campus", lat: 3.1718, lng: 101.7214 }] },
    { name: 'Universiti Kebangsaan Malaysia (UKM)', country: 'Malaysia', locations: [{ name: "Bangi Campus Library", lat: 2.9230, lng: 101.7691 }] },
    { name: 'Universiti Putra Malaysia (UPM)', country: 'Malaysia', locations: [{ name: "Serdang Engineering", lat: 2.9920, lng: 101.7105 }] },
    { name: 'Universiti Sains Malaysia (USM)', country: 'Malaysia', locations: [{ name: "Penang Main Campus", lat: 5.3553, lng: 100.2947 }, { name: "Engineering Campus", lat: 5.1472, lng: 100.4905 }] },
    { name: 'Universiti Teknologi MARA (UiTM)', country: 'Malaysia', locations: [{ name: "Shah Alam Library", lat: 3.0673, lng: 101.4989 }] },
    { name: 'International Islamic University Malaysia (IIUM)', country: 'Malaysia', locations: [{ name: "Gombak Campus", lat: 3.2514, lng: 101.7347 }] },
    { name: 'Universiti Utara Malaysia (UUM)', country: 'Malaysia', locations: [{ name: "Sintok Campus", lat: 6.4580, lng: 100.5050 }] },
    { name: 'Universiti Malaysia Sarawak (UNIMAS)', country: 'Malaysia', locations: [{ name: "Kota Samarahan", lat: 1.4650, lng: 110.4260 }] },
    { name: 'Universiti Malaysia Sabah (UMS)', country: 'Malaysia', locations: [{ name: "Kota Kinabalu", lat: 6.0360, lng: 116.1190 }] },
    { name: 'Universiti Teknikal Malaysia Melaka (UTeM)', country: 'Malaysia', locations: [{ name: "Durian Tunggal", lat: 2.3130, lng: 102.3210 }] },
    { name: 'Universiti Tun Hussein Onn Malaysia (UTHM)', country: 'Malaysia', locations: [{ name: "Batu Pahat", lat: 1.8540, lng: 103.0860 }] },
    { name: 'Universiti Malaysia Pahang (UMPSA)', country: 'Malaysia', locations: [{ name: "Pekan Campus", lat: 3.5430, lng: 103.4290 }] },
    { name: 'Universiti Malaysia Perlis (UniMAP)', country: 'Malaysia', locations: [{ name: "Arau Campus", lat: 6.4460, lng: 100.2760 }] },
    { name: 'Universiti Sultan Zainal Abidin (UniSZA)', country: 'Malaysia', locations: [{ name: "Gong Badak", lat: 5.3970, lng: 103.0800 }] },
    { name: 'Universiti Malaysia Terengganu (UMT)', country: 'Malaysia', locations: [{ name: "Kuala Terengganu", lat: 5.4080, lng: 103.0880 }] },
    { name: 'Universiti Malaysia Kelantan (UMK)', country: 'Malaysia', locations: [{ name: "Bachok Campus", lat: 6.0020, lng: 102.4080 }] },
    { name: 'Universiti Pertahanan Nasional Malaysia (UPNM)', country: 'Malaysia', locations: [{ name: "Sg Besi", lat: 3.0500, lng: 101.7240 }] },
    { name: 'Universiti Pendidikan Sultan Idris (UPSI)', country: 'Malaysia', locations: [{ name: "Tanjung Malim", lat: 3.6850, lng: 101.5230 }] },
    { name: 'Taylor\'s University', country: 'Malaysia', locations: [{ name: "Lakeside Campus", lat: 3.0620, lng: 101.6160 }] },
    { name: 'Sunway University', country: 'Malaysia', locations: [{ name: "Sunway Campus", lat: 3.0673, lng: 101.6033 }] },
    { name: 'Monash University Malaysia', country: 'Malaysia', locations: [{ name: "Bandar Sunway", lat: 3.0648, lng: 101.6010 }] },
    { name: 'University of Nottingham Malaysia', country: 'Malaysia', locations: [{ name: "Semenyih", lat: 2.9450, lng: 101.8740 }] },
    { name: 'Heriot-Watt University Malaysia', country: 'Malaysia', locations: [{ name: "Putrajaya", lat: 2.9090, lng: 101.6705 }] },
    { name: 'Asia Pacific University (APU)', country: 'Malaysia', locations: [{ name: "TPM Cyberjaya", lat: 3.0560, lng: 101.6910 }] },
    { name: 'Multimedia University (MMU)', country: 'Malaysia', locations: [{ name: "Cyberjaya", lat: 2.9276, lng: 101.6421 }] },
    { name: 'Universiti Tenaga Nasional (UNITEN)', country: 'Malaysia', locations: [{ name: "Putrajaya/Kajang", lat: 2.9728, lng: 101.7310 }] },
    { name: 'UCSI University', country: 'Malaysia', locations: [{ name: "KL Campus", lat: 3.0790, lng: 101.7330 }] },
    { name: 'Universiti Tunku Abdul Rahman (UTAR)', country: 'Malaysia', locations: [{ name: "Kampar Campus", lat: 4.3390, lng: 101.1410 }, { name: "Sungai Long", lat: 3.0400, lng: 101.7940 }] },
    { name: 'SEGi University', country: 'Malaysia', locations: [{ name: "Kota Damansara", lat: 3.1490, lng: 101.5770 }] },
    { name: 'Management and Science University (MSU)', country: 'Malaysia', locations: [{ name: "Shah Alam", lat: 3.0780, lng: 101.5510 }] },
    { name: 'HELP University', country: 'Malaysia', locations: [{ name: "Subang Bestari", lat: 3.1610, lng: 101.5170 }] },
    { name: 'INTI International University', country: 'Malaysia', locations: [{ name: "Nilai Campus", lat: 2.8130, lng: 101.7610 }] },
    { name: 'Nilai University', country: 'Malaysia', locations: [{ name: "Nilai", lat: 2.8160, lng: 101.7620 }] },
    { name: 'Swinburne University of Technology Sarawak', country: 'Malaysia', locations: [{ name: "Kuching", lat: 1.5310, lng: 110.3570 }] },
    { name: 'Curtin University Malaysia', country: 'Malaysia', locations: [{ name: "Miri", lat: 4.5120, lng: 114.0180 }] },
    { name: 'Xiamen University Malaysia', country: 'Malaysia', locations: [{ name: "Sepang", lat: 2.8330, lng: 101.7080 }] },
    { name: 'Quest International University', country: 'Malaysia', locations: [{ name: "Ipoh", lat: 4.5910, lng: 101.0960 }] },
    { name: 'Infrastructure University Kuala Lumpur (IUKL)', country: 'Malaysia', locations: [{ name: "Kajang", lat: 2.9790, lng: 101.7370 }] },
    { name: 'Other UK University', country: 'UK', locations: [{ name: "Default (London)", lat: 51.5074, lng: -0.1278 }] },
    { name: 'Other Malaysian University', country: 'Malaysia', locations: [{ name: "Default (KL)", lat: 3.1390, lng: 101.6869 }] }
];
